import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.surface },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.outlineVariant + '66',
  },
  headerBtn: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: 17, fontWeight: '800', color: colors.primary },
  summary: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    paddingHorizontal: 20,
    paddingVertical: 18,
    backgroundColor: colors.surfaceContainerLow,
    borderBottomWidth: 1,
    borderBottomColor: colors.outlineVariant + '44',
  },
  summaryLabel: { fontSize: 12, fontWeight: '700', color: colors.outline, textTransform: 'uppercase' },
  summaryValue: { fontSize: 22, fontWeight: '900', color: colors.primary, marginTop: 4 },
  summaryHint: { fontSize: 13, color: colors.onSurfaceVariant, marginTop: 6, lineHeight: 18 },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 },
  listContent: { padding: 20, paddingBottom: 40, gap: 12 },
  empty: { alignItems: 'center', paddingVertical: 40, paddingHorizontal: 16 },
  emptyTitle: { marginTop: 12, fontSize: 16, fontWeight: '800', color: colors.primary },
  emptySub: {
    marginTop: 8,
    fontSize: 14,
    color: colors.onSurfaceVariant,
    textAlign: 'center',
    lineHeight: 20,
  },
  card: {
    backgroundColor: colors.surfaceContainerLowest,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.outlineVariant + '55',
  },
  cardTop: { gap: 8 },
  caseTitle: { fontSize: 15, fontWeight: '800', color: colors.primary },
  starsRow: { flexDirection: 'row', gap: 2 },
  comment: {
    marginTop: 10,
    fontSize: 14,
    color: colors.onSurface,
    lineHeight: 21,
    fontStyle: 'italic',
  },
  noComment: { marginTop: 8, fontSize: 13, color: colors.outline, fontStyle: 'italic' },
  clientHint: { marginTop: 10, fontSize: 12, fontWeight: '600', color: colors.secondary },
  date: { marginTop: 6, fontSize: 11, color: colors.outline },
});
