import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.surface },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.outlineVariant + '44',
  },
  headerBtn: { width: 72, alignItems: 'flex-start' },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '800',
    color: colors.primary,
  },
  markAllBtn: { width: 72, alignItems: 'flex-end' },
  markAllText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.secondary,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  emptyTitle: {
    marginTop: 16,
    fontSize: 18,
    fontWeight: '800',
    color: colors.primary,
  },
  emptySub: {
    marginTop: 8,
    textAlign: 'center',
    fontSize: 14,
    color: colors.onSurfaceVariant,
    lineHeight: 22,
  },
  list: { paddingHorizontal: 16, paddingBottom: 24, paddingTop: 8 },
  row: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 12,
    marginBottom: 8,
    backgroundColor: colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: colors.outlineVariant + '33',
  },
  rowUnread: {
    backgroundColor: colors.primaryContainer + '55',
    borderColor: colors.primary + '22',
  },
  iconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surfaceContainerHigh,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconWrapUnread: {
    backgroundColor: colors.surfaceContainerHighest,
  },
  rowBody: { flex: 1, minWidth: 0 },
  rowTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.primary,
  },
  rowTitleBold: { fontWeight: '800' },
  rowBodyText: {
    marginTop: 4,
    fontSize: 13,
    color: colors.onSurfaceVariant,
    lineHeight: 18,
  },
  rowTime: {
    marginTop: 8,
    fontSize: 11,
    fontWeight: '600',
    color: colors.outline,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.secondary,
    marginTop: 6,
  },
});
